plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

group = "com.gflix.extcore"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.1"
}

compileTestJava {
    options.encoding = "UTF-8"
}

test {
    useJUnit()
}
